config/routes.rb
Rails.application.routes.draw do
  get '/lists/:id/results' => 'lists#results', as: 'list_results'
  post '/list/:id', :controller => 'lists', :action => 'send_results'
  resources :lists

  get '/questions/:id/set_answer' => 'questions#set_answer', as: 'set_answer_question'
  patch "questions/:id/set_answer", to: "questions#send_answer"
  resources :questions


  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
  end

  root :to => 'authentication#index'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user, class_name: "User"
  mount_uploaders :images, QuestionImagesUploader
  has_many :results, :dependent => :delete_all
  has_and_belongs_to_many :lists, :dependent => :delete_all

  validates_presence_of :title, :on => :create, :message => "can't be blank"
  validates_presence_of :description, :on => :create, :message => "can't be blank"
  validates_presence_of :images, :on => :create, :message => "needs at least 2 images"

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy, :set_answer, :send_answer]
  before_action :set_current_user
  before_action :check_professor

  # GET /questions
  # GET /questions.json
  def index
    @resource = "Question"
    @resource_new_path = new_question_path
    if @user.role.name == "professor"
      @questions = @user.questions.paginate(page: params[:page], per_page: 6)
      if @questions.count == 0
        @noResource = "Ahh boo ;(! <br /> You have no questions created.".html_safe
      end
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id = @user.id
    if @question.save
      redirect_to set_answer_question_path(@question)
    else
      redirect_to new_question_path
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
      if @question.update(question_params)
        redirect_to set_answer_question_path(@question)
      end
  end

  def set_answer
  end

  def send_answer
    if @question.update_attribute(:answer, params[:question][:answer].split(',').map { |s| s.to_i })
      redirect_to questions_path, notice: 'Question was created and answer was set.'
    else
      redirect_to set_answer_question_path(@question)
    end
  end


  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :description, :images, {images: []}, :answer, answer: [])
    end


  private
  #Set Current user on platform
  def set_current_user
    @user = current_user
  end

  def check_professor
    if @user.role.name != "professor"
      redirect_to root_path
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_drag.html.erb
<div class="row col-md-10 col-md-offset-1">
    <% if current_page?(set_answer_question_path) %>
      <h1 class='center'>Set Answer</h1>
      <% else %>
        <script>
          var question_answer = <%= @question.answer %>;
          console.log(question_answer);
        </script>
        <h1 class='center'>Try Question</h1><br>
        <h2><b>Title: </b><span><%= @question.title %></span></h2><br>
        <h4><b>Description:</b></h4>
        <p><%= @question.description%></p>
      <% end %>
  <ol id="list_images" class="list_style custom_counter connectedSortable">
    <% @question.images.each_with_index do |i, id| %>
    <li id="<%= id %>">
      <img src="<%= i.url %>">
    </li>
    <% end %>
  </ol>
  <ol id="list_answer" class="list_style connectedSortable custom_counter">
  </ol>
</div>
  <% if current_page?(set_answer_question_path) %>
    <div class="row col-md-2 col-md-offset-5 center row-mt">
      <a class="answer_btn">Set Answer</a>
    </div>
      <div class="row col-md-2 col-md-offset-5 center row-mt">
        <%= form_for @question, :url => {:action => "send_answer"} do |f| %>
        <%= f.hidden_field :answer, :class => "answer_input" %>
        <%= f.submit "Update Question", :class => "create_resource_new" %>
        <% end %>
      </div>
  <% else %>
    <div class="row col-md-2 col-md-offset-5 center row-mt">
      <a class="answer_question_btn">Send Answer</a>
    </div>
    <div class="row col-md-8 col-md-offset-2 center row-mt">
      <h1 id="feedback" class="center"></h1>
      <ul id="errors">
      </ul>
    </div>
  <% end %>

app/views/questions/_form.html.erb
<div id="form_container" class="panel panel-default col-md-4 col-md-offset-4">
  <div id="form_title_container" class="panel-heading">
    <h3 class="panel-title form_title">
      <% if current_page?(new_question_path) %>
        Create
      <% else %>
        Edit
      <% end %>
      Question
    </h3>
  </div>
  <div class="panel-body">
    <%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title, :class => "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_area :description, :class => "form-control resize_disable" %>
  </div>
  <div class="form-group">
    <%= f.label :images %><br />
    <%= f.file_field :images, multiple: true %>
  </div>
  <div class="field">
    <%= f.submit "Submit", :class => "create_resource_new" %>
  </div>
<% end %>
<div class="field">
  <%= link_to 'Cancel', questions_path, :class => "back_link cancel_resource_new" %>
</div>
  </div>
</div>

app/views/questions/edit.html.erb
<%= render 'form', question: @question %>

app/views/questions/index.html.erb
<div class="row">
  <!-- START QUESTION COUNT-->
  <% if @questions.count != 0 %>
    <div id="index_table_container" class="panel panel-default col-md-8 col-md-offset-2">
      <div id="index_table_header" class="panel-heading">Your Questions</div>
      <table class="table">
        <tr>
          <th class="cell_width text_center">Title</th>
          <th class="cell_width text_center">Description</th>
          <th class="cell_width text_center">Actions</th>
        </tr>
        <!-- START .EACH-->
        <% @questions.each do |question| %>
        <tr>
          <td class="no-border"><%= truncate(question.title, :length => 40, :separator => ' ')%></td>
          <td><%= truncate(question.description, :length => 70, :separator => ' ')%></td>
          <td class="text_center">
            <%= link_to 'Show', question_path(question), :class => "td_show" %>
            <%= link_to 'Edit', edit_question_path(question), :class => "td_edit" %>
          </td>
        </tr>
        <% end %>
        <!-- END .EACH-->
      </table>
    </div>
    <div class="row">
      <%= will_paginate @questions, :class => "col-md-2 col-md-offset-5", :page_links => false %>
    </div>
    <%= render "shared/createResource" %>
  <% else %>
  <%= render "shared/noResource" %>
  <% end %>
  <!-- END QUESTION COUNT -->
</div>

app/views/questions/new.html.erb
<%= render 'form', question: @question %>

app/views/questions/set_answer.html.erb
<%= render 'drag'%>

app/views/questions/show.html.erb
<%= render 'drag' %>