config/routes.rb
Rails.application.routes.draw do
  get '/lists/:id/results' => 'lists#results', as: 'list_results'
  post '/list/:id', :controller => 'lists', :action => 'send_results'
  resources :lists

  get '/questions/:id/set_answer' => 'questions#set_answer', as: 'set_answer_question'
  patch "questions/:id/set_answer", to: "questions#send_answer"
  resources :questions


  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
  end

  root :to => 'authentication#index'
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  validates_presence_of :title, :on => :create, :message => "can't be blank"
  validates_presence_of :list_questions, :on => :create, :message => "can't be blank and must have at least 2 questions"
  has_many :results, :dependent => :delete_all
  has_and_belongs_to_many :questions
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  require 'will_paginate/array'
  before_action :set_list, only: [:show, :edit, :update, :destroy, :results]
  before_action :set_current_user
  before_action :check_professor, only: [:new, :edit, :update, :destroy]
  # GET /lists
  # GET /lists.json
  def index
    @resource = "List"
    @resource_new_path = new_list_path
    if @user.role.name == "professor"
      @lists = @user.lists.paginate(page: params[:page], per_page: 6)
      if @lists.count == 0
        @noResource = "Ahh boo ;(! <br /> You have no lists created.".html_safe
      end
    else
      @lists = List.all.paginate(page: params[:page], per_page: 6)
      if @lists.count == 0
        @noResource = "Ahh boo ;(! <br /> You have no lists to try.".html_safe
      end
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
      @questions = []
      @result = Result.new
      @ids = @list.list_questions
      @ids.each do |i|
        @q = Question.find(i)
        @questions << @q
      end
      @questions = @questions.paginate(page: params[:page], per_page: 1)
  end


  def send_results
    @result = Result.create(result_params)
    @result.save
  end

  def results
    if all_questions_answered_status(@user, @list)
      @correct = Result.where(:user_id => current_user.id, :list_id => @list.id, :correct => true).group(:correct).count
      @incorrect = Result.where(:user_id => current_user.id, :list_id => @list.id, :correct => false).group(:correct).count
      
      build_questions_for_result
      
      @questions = @questions.paginate(page: params[:page], per_page: 5)
      
    else
      redirect_to lists_path
    end
  end



  # GET /lists/new
  def new
    @list = List.new
    @questions = @user.questions
  end

  # GET /lists/1/edit
  def edit
    if any_question_answered(@user, @list)
      redirect_to lists_path
    end
    @questions = @user.questions
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    @list.user_id = @user.id
    @list.list_questions = params[:list][:list_questions].split(',').map { |s| s.to_i }
      if @list.save
        redirect_to lists_path
      else
        redirect_to new_list_path
      end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    params[:list][:list_questions] = params[:list][:list_questions].split(',').map { |s| s.to_i }
      if @list.update(list_params)
        redirect_to lists_path
      else
        redirect_to new_list_path
      end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :list_questions, list_questions: [])
    end

    private
    #Set Current user on platform
    def set_current_user
      @user = current_user
    end

    private
    def check_professor
      if @user.role.name != "professor"
        redirect_to root_path
      end
    end

    def result_params
      params.require(:result).permit(:user_id, :question_id, :list_id, :correct)
    end

    def all_questions_answered_status(user, list)
      @attempted = Result.where(:user_id => user.id, :list_id => list.id)
      if @attempted.count == list.list_questions.count
        return true
      else
        return false
      end
    end

    helper_method :all_questions_answered_status
    
    
    def any_question_answered(user, list)
      @attempted = Result.where(:user_id => user.id, :list_id => list.id)
      if @attempted.count > 0
        return true
      else
        return false
      end
    end
    
    helper_method :any_question_answered

    def build_questions_for_result
      @questions = []
      @results = Result.where(:user_id => @user.id, :list_id => @list.id)
      @corrects = 0
      @total = @results.count
      @results.each do |r|
        @q = Question.find(r.question_id)
        @qr = r.correct
        if @qr
          @corrects += 1
        end
        @questions << [@q, @qr]
      end
      @percent = ((@corrects.to_f / @total.to_f) * 100).round
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_drag.html.erb
<div class="row col-md-10 col-md-offset-1">
   <h1 class='center'>Solve List</h1>
   <% @questions.each do |q| %>
   <div class="question_field">
      <script>
         var question_answer = <%= q.answer %>;
         console.log(question_answer);
      </script>
      <h2><b>Title: </b><span><%= q.title %></span></h2>
      <br>
      <h4><b>Description:</b></h4>
      <p><%= q.description%></p>
      <ol id="list_images" class="list_style custom_counter connectedSortable">
         <% q.images.each_with_index do |i, id| %>
         <li id="<%= id %>">
            <img src="<%= i.url %>">
         </li>
         <% end %>
      </ol>
      <ol id="list_answer" class="list_style connectedSortable custom_counter">
      </ol>
   </div>
   <% @attempted = Result.where(:user_id => @user.id, :list_id => @list.id, :question_id => q.id) %>
   <%  if @attempted.count == 0 %>
   <div class="row col-md-2 col-md-offset-5 center row-mt">
      <%= form_for @result, :url => {:controller => 'lists', :action => "send_results"}, :method => 'post' do |f| %>
      <%= f.hidden_field :user_id, :value => @user.id %>
      <%= f.hidden_field :list_id, :value => @list.id %>
      <%= f.hidden_field :correct, :class => 'correct_input' %>
      <%= f.hidden_field :question_id, :value => q.id %>
      <%= f.submit "Send Answer", :class => "question_list_answer" %>
      <% end %>
   </div>
   <% else %>
   <h2 class="center">Already answered this question.<br />Go to the next one!</h2>
   <div class="hide_prev">
      <% if @questions.total_pages != @questions.current_page %>
      <%= will_paginate @questions, :class => "col-md-4 col-md-offset-4 center", :page_links => false %>
      <% else %>
      <div class="row col-md-2 col-md-offset-5 center row-mt">
         <%= link_to 'See Results', list_results_path(@list), :class => "finish_list_btn" %>
      </div>
      <% end %>
   </div>
   <% end %>
   <% end %>
   <div class="row col-md-8 col-md-offset-2 center row-mt">
      <h1 id="feedback" class="center"></h1>
      <ul id="errors">
      </ul>
   </div>
   <div class="hide_prev">
      <% if @questions.total_pages != @questions.current_page %>
      <%= will_paginate @questions, :class => "col-md-4 col-md-offset-4 center hidden_paginate", :page_links => false %>
      <% else %>
      <div class="row col-md-2 col-md-offset-5 center row-mt">
         <%= link_to 'See Results', list_results_path(@list), :class => "finish_list_btn disable_a_href" %>
      </div>
      <% end %>
   </div>
</div>

app/views/lists/_form.html.erb
<% if @questions.count >= 2 %>
  <div id="form_container" class="panel panel-default col-md-4 col-md-offset-4">
    <div id="form_title_container" class="panel-heading">
      <h3 class="panel-title form_title">
        <% if current_page?(new_list_path) %>
          Create
        <% else %>
          Edit
        <% end %>
        List
      </h3>
    </div>
    <div class="panel-body">
        <%= form_for(@list) do |f| %>
          <% if @list.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@list.errors.count, "error") %> prohibited this post from being saved:</h2>
              <ul>
              <% @list.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="form-group">
            <%= f.label :title %><br />
            <%= f.text_field :title, :class => "form-control"%>
          </div>
          <div class="form-group">
            <%= select_tag nil, options_from_collection_for_select(@questions, "id", "title"), multiple: true, :class => "list_container", :id => "questions_container" %>
            <div id="throw_container">
              <input type="button" id="throw_right" value=">" />
              <br>
              <input type="button" id="throw_left" value="<" />
            </div>
            <%= select_tag nil, nil,multiple: true, :class => "list_container", :id => "questions_list_container" %>
          </div>
          <%= f.hidden_field :list_questions %>
          <div class="field">
            <%= f.submit "Submit", :class => "create_resource_new" %>
          </div>
        <% end %>
        <div class="field">
          <%= link_to 'Cancel', lists_path, :class => "back_link cancel_resource_new" %>
        </div>
    </div>
  </div>
<% else %>
<h2 class="center">Create at least 2 questions to create a list!</h2>
<% end %>

app/views/lists/edit.html.erb
<%= render 'form', list: @list %>

app/views/lists/index.html.erb
<div class="row">
  <!-- START LIST COUNT-->
  <% if @lists.count != 0 %>
    <div id="index_table_container" class="panel panel-default col-md-8 col-md-offset-2">
      <div id="index_table_header" class="panel-heading">Your lists</div>
      <table class="table">
        <tr>
          <th class="cell_width center">Title</th>
          <th class="cell_width center">Actions</th>
          <th class="cell_width center">Status</th>
        </tr>
        <!-- START .EACH-->
        <% @lists.each do |list| %>
        <tr>
          <td class="no-border"><%= truncate(list.title, :length => 40, :separator => ' ')%></td>
          <td class="center">
            <% if !all_questions_answered_status(current_user, list) %>
              <%= link_to 'Try', list_path(list), :class => "td_show" %>
            <% end %>
            <% if @user.role.name == 'professor' %>
              <% if !any_question_answered(current_user, list) %>
              <%= link_to 'Edit', edit_list_path(list), :class => "td_edit" %>
              <% end %>
            <% end %>
            <% if all_questions_answered_status(current_user, list) %>
            <%= link_to 'Results', list_results_path(list), :class => "td_results" %>
            <% end %>
          </td>
          <% if all_questions_answered_status(current_user, list) %>
            <td class="status_complete">COMPLETED</td>
          <% elsif Result.where(:user_id => current_user.id, :list_id => list.id).count == 0 %>
            <td class="status_incomplete">NOT ATTEMPTED</td>
          <% else %>
            <td class="status_inprogress">IN PROGRESS</td>
          <% end %>
        </tr>
        <% end %>
        <!-- END .EACH-->
      </table>
    </div>
    <div class="row">
      <%= will_paginate @lists, :class => "col-md-2 col-md-offset-5", :page_links => false %>
    </div>
    <%= render "shared/createResource" %>
  <% else %>
  <%= render "shared/noResource" %>
  <% end %>
  <!-- END LIST COUNT -->
</div>

app/views/lists/new.html.erb
<%= render 'form', list: @list %>

app/views/lists/results.html.erb
<h2 class="center">Total Percent Score: <%= @percent %>%</h2>
<div class="row col-md-10 col-md-offset-1">
    <div id="index_table_container" class="panel panel-default col-md-8 col-md-offset-2">
        <div id="index_table_header" class="panel-heading">Results for List:
            <%= @list.title %>
        </div>
        <table class="table">
            <tr>
                <th class="cell_width center">Question Title</td>
                <th class="cell_width center">Status</td>
            </tr>
            <% @questions.each do |a| %>
                <tr>
                    <td class="center">
                        <%= a[0].title %>
                    </td>
                    <% if a[1]== true %>
                        <td class="center status_complete">&#10004</td>
                    <% else %>
                        <td class="center status_incomplete">X</td>
                    <% end %>
                </tr>
            <% end %>
        </table>
    </div>
    <%= will_paginate @questions, :class => "col-md-2 col-md-offset-5 results_paginate", :page_links => false %>
</div>
<%= pie_chart Correct: @correct[true], Incorrect: @incorrect[false] %>

app/views/lists/show.html.erb
<%= render "drag" %>