config/routes.rb
Rails.application.routes.draw do
  get '/lists/:id/results' => 'lists#results', as: 'list_results'
  post '/list/:id', :controller => 'lists', :action => 'send_results'
  resources :lists

  get '/questions/:id/set_answer' => 'questions#set_answer', as: 'set_answer_question'
  patch "questions/:id/set_answer", to: "questions#send_answer"
  resources :questions


  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
  end

  root :to => 'authentication#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monografia</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <header>
        <nav id="main_navbar" class="navbar navbar-default">
          <div id="main_container" class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a id="main_nav_logo" class="navbar-brand" href="#">Slife</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul id="main_nav_menu" class="nav navbar-nav">
                <% if current_user.role.name == 'professor' %>
                <li class="<%= 'active' if current_page?(questions_path) %>"><%= link_to "Questions", questions_path %> <span class="sr-only">(current)</span></li>
                <% end %>
                <li class="<%= 'active' if current_page?(lists_path) %>"><%= link_to "Lists", lists_path %></li>
              </ul>
              <ul id="main_nav_user_menu" class="nav navbar-nav navbar-right">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= @user.first_name %><span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to('Edit profile', edit_user_registration_path) %></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
                  </ul>
                </li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
      </header>
    <div id="wrapper" class="container">
      <%= yield %>

    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monografia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application-devise', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application-devise', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper" class="container">
      <%= yield %>
    </div>
  </body>
</html>